### ISSUE TITLE
Any tutorial for unraid

### ISSUE THREAD

**Issue by ggkkomando** [xavier-hernandez/docker-external-ip#3]
Hi,
I am new to unraid and would like to test out your app. But I really dont know how to configure and use them. I get to install them but not sure how to use the notification function. like what is the user id etc. could you give me a tutorial.

**Comment by xavier-hernandez** [comment]
@ggkkomando what notification are you trying to use? By default, I'm using Pushover.

**Comment by xavier-hernandez** [comment]
@ggkkomando closing. Conversation resuming in Unraid forum, https://forums.unraid.net/topic/125786-support-xavierh-external-ip/#comment-1179601 .
