### ISSUE TITLE
problem with pushing new image

### ISSUE THREAD

**Issue by xavier-hernandez** [xavier-hernandez/docker-external-ip#5]
@MrGreaterThan looks like I'm having issues pushing out a new build, with your changes. I'm looking into it.

**Comment by MrGreaterThan** [comment]
It's actually my first pull request ever. Apologies if I broke something.

**Comment by xavier-hernandez** [comment]
@MrGreaterThan no, its not you. Thanks for the pull request. Builds should be automated but it's not working. I should get it working tomorrow or Thursday.

**Comment by xavier-hernandez** [comment]
Finally fixed it. Image has bene updated.
